### ISSUE TITLE
docker拉取镜像后 root_db_1无法启动 提示语法错误

### ISSUE THREAD

**Issue by madman43** [MoeNetwork/Tieba-Cloud-Sign#123]
+ deluser core,
+ delgroup core,
+ addgroup --system --gid="500" core,
delgroup: unknown group core,
+ adduser --system --disabled-password --no-create-home --ingroup="core" --gecos="core" --shell="/bin/bash" --uid="500" core,
+ mysql_install_db --user="core" --datadir="/var/lib/mysql" ,
Installing MariaDB/MySQL system tables in '/var/lib/mysql' ...,
/usr/bin/mysqld: Can't create file '/var/log/mysql/error.log' (errno: 13 "Permission denied"),
2021-08-28  8:19:45 1 [Warning] Failed to load slave replication state from table mysql.gtid_slave_pos: 1017: Can't find file: './mysql/' (errno: 2 "No such file or directory"),
OK,
,
To start mysqld at boot time you have to copy,
support-files/mysql.server to the right place for your system,
,
,
Two all-privilege accounts were created.,
One is root@localhost, it has no password, but you need to,
be system 'root' user to connect. Use, for example, sudo mysql,
The second is core@localhost, it has no password either, but,
you need to be the system 'core' user to connect.,
After connecting you can set the password, if you would need to be,
able to connect as any of these users with a password and without sudo,
,
See the MariaDB Knowledgebase at https://mariadb.com/kb or the,
MySQL manual for more instructions.,
,
You can start the MariaDB daemon with:,
cd '/usr' ; /usr/bin/mysqld_safe --datadir='/var/lib/mysql',
,
You can test the MariaDB daemon with mysql-test-run.pl,
cd '/usr/mysql-test' ; perl mysql-test-run.pl,
,
Please report any problems at https://mariadb.org/jira,
,
The latest information about MariaDB is available at https://mariadb.org/.,
You can find additional information about the MySQL part at:,
https://dev.mysql.com,
Consider joining MariaDB's strong and vibrant community:,
https://mariadb.org/get-involved/,
,
+ mysqld_safe --no-watch --skip-grant-tables --user="core" ,
210828 08:19:46 mysqld_safe Logging to '/var/log/mysql/error.log'.,
210828 08:19:46 mysqld_safe Starting mariadbd daemon with databases from /var/lib/mysql,
> Update Privileges,
+ mysql --protocol="socket" --user="root" --init-command="SET @@SESSION.SQL_LOG_BIN=0;" --execute="FLUSH PRIVILEGES; DELETE FROM mysql.user WHERE user IN ('') OR host NOT IN ('localhost', '%'); CREATE USER IF NOT EXISTS 'root'@'localhost' IDENTIFIED BY 'janejane123456'; ALTER USER 'root'@'localhost' IDENTIFIED BY 'janejane123456'; GRANT ALL ON *.* TO 'root'@'localhost' WITH GRANT OPTION; CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'janejane123456'; ALTER USER 'root'@'%' IDENTIFIED BY 'janejane123456'; GRANT ALL ON *.* TO 'root'@'%' WITH GRANT OPTION; CREATE DATABASE IF NOT EXISTS 'tiebacloud'; FLUSH PRIVILEGES;" ,
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''tiebacloud'' at line 1,
/usr/lib/ruby/gems/2.7.0/gems/docker_core-0.0.22/lib/docker_core.rb:136:in `system': Command failed with exit 1: mysql --protocol="socket" --user="root" --init-command="SET @@SESSION.SQL_LOG_BIN=0;" --execute="FLUSH PRIVILEGES; DELETE FROM mysql.user WHERE user IN ('') OR host NOT IN ('localhost', '%'); CREATE USER IF NOT EXISTS 'root'@'localhost' IDENTIFIED BY 'janejane123456'; ALTER USER 'root'@'localhost' IDENTIFIED BY 'janejane123456'; GRANT ALL ON *.* TO 'root'@'localhost' WITH GRANT OPTION; CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'janejane123456'; ALTER USER 'root'@'%' IDENTIFIED BY 'janejane123456'; GRANT ALL ON *.* TO 'root'@'%' WITH GRANT OPTION; CREATE DATABASE IF NOT EXISTS 'tiebacloud'; FLUSH PRIVILEGES;"  (RuntimeError),
	from /usr/lib/ruby/gems/2.7.0/gems/docker_core-0.0.22/lib/docker_core.rb:136:in `run',
	from /usr/local/bin/image/mariadb.rb:104:in `update_privileges',
	from /usr/lib/ruby/gems/2.7.0/gems/docker_core-0.0.22/lib/docker_core.rb:153:in `call',
	from /usr/lib/ruby/gems/2.7.0/gems/docker_core-0.0.22/lib/docker_core.rb:153:in `invoke',
	from /usr/local/bin/image/mariadb.rb:116:in `setup_database',
	from /usr/local/bin/image/mariadb.rb:141:in `main',
	from /usr/local/bin/docker_run.rb:5:in `<main>'

**Comment by madman43** [comment]
更换数据库解决了，
