### ISSUE TITLE
数据库启动失败

### ISSUE THREAD

**Issue by rickychaw** [MoeNetwork/Tieba-Cloud-Sign#245]
- 

- [Y ] 我已升级贴吧云签到到最新版本，并且运行了升级脚本

- [ Y] 我已搜索过 Issue 区，没有找到相关问题

# 问题描述

### docker-compose启动时db容器无法启动，报错

```tieba-db-1   | + deluser core
tieba-db-1   | + delgroup core
tieba-db-1   | + addgroup --system --gid="500" core
tieba-db-1   | addgroup: group 'core' in use
tieba-db-1   | /usr/lib/ruby/gems/3.1.0/gems/docker_core-0.0.42/lib/docker_core.rb:386:in `system': Command failed with exit 1: addgroup --system --gid="500" core (RuntimeError)
tieba-db-1   |  from /usr/lib/ruby/gems/3.1.0/gems/docker_core-0.0.42/lib/docker_core.rb:386:in `run'
tieba-db-1   |  from /usr/lib/ruby/gems/3.1.0/gems/docker_core-0.0.42/lib/docker_core.rb:620:in `update_user'
tieba-db-1   |  from /usr/local/bin/image/mariadb.rb:138:in `main'
tieba-db-1   |  from /usr/local/bin/docker_run.rb:5:in `<main>'
tieba-db-1 exited with code 1

# 复现步骤
<!-- 请在下一行详细地描述你经过了哪些步骤产生了这个问题 -->
### 每次复现

# 环境
<!-- 请在下面详细地描述本程序的运行环境 -->

 - 云签到版本：**5.0**
 - 服务器系统和版本：**armbian 5.62**
 - 云签到是否在 Docker 中运行：**docker-compose**
 - PHP 版本：
 - MySQL 版本：

**Comment by Chun-J1** [comment]
我也这样
