### ISSUE TITLE
Uncaught exception 'Exception' with message

### ISSUE THREAD

**Issue by archerlll** [MoeNetwork/Tieba-Cloud-Sign#59]
Fatal error: Uncaught exception 'Exception' with message 'MySQL 语句执行错误：<br/><b>语句：</b>SELECT * FROM tc_options<br/><b>错误：</b>#1146 - Table 'yun.tc_options' doesn't exist' in /www/wwwroot/yun/lib/class.mysqli.php:120 Stack trace: #0 /www/wwwroot/yun/lib/reg.php(33): wmysql->query('SELECT * FROM t...') #1 /www/wwwroot/yun/init.php(48): require('/www/wwwroot/yu...') #2 /www/wwwroot/yun/index.php(8): require('/www/wwwroot/yu...') #3 {main} thrown in /www/wwwroot/yun/lib/class.mysqli.php on line 120

求指点

**Comment by stevenzhu25** [comment]
它上面写的清清楚楚的…

yun.tc_options 这张数据表不存在…
