### ISSUE TITLE
各位朋友，如果在执行docker-composedocker-compose up -d时报错，请试试我的办法

### ISSUE THREAD

**Issue by hongxiaoxin** [MoeNetwork/Tieba-Cloud-Sign#93]
错误代码是
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 80, in main
  File "compose/cli/main.py", line 189, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 222, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2739] Failed to execute script docker-compose

```
很简单，只要
`systemctl start docker`
即可
**（只适用于能有启动systemctl的环境）**
其他系统的朋友去找你们系统的办法，目的仅是启动docker这个程序（在有安装的情况下），似乎是因为程序没有启动，所以才会导致“failed to execute script”

**Comment by lujiaxuan666** [comment]
感谢老哥

**Comment by n0099** [comment]
```bash
service docker start
```

**Comment by skbfzx** [comment]
在执行docker-compose up -d时报错
ERROR: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version

请教大神，如何解决？
